2021-08-23 14:53:27,170 INFO    MainThread:69158 [internal.py:wandb_internal():63] W&B internal server running at pid: 69158
2021-08-23 14:53:27,172 DEBUG   HandlerThread:69158 [handler.py:handle_request():55] handle_request: check_version
2021-08-23 14:53:27,172 INFO    WriterThread:69158 [datastore.py:open_for_write():76] open: /home/sebastian/Documents/CQL/CQL-DQN/wandb/run-20210823_145326-ouvvtcg9/run-ouvvtcg9.wandb
2021-08-23 14:53:27,173 DEBUG   SenderThread:69158 [sender.py:send():90] send: header
2021-08-23 14:53:27,173 DEBUG   SenderThread:69158 [sender.py:send():90] send: request
2021-08-23 14:53:27,173 DEBUG   SenderThread:69158 [sender.py:send_request():99] send_request: check_version
2021-08-23 14:53:27,175 DEBUG   Thread-4  :69158 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): pypi.org:443
2021-08-23 14:53:27,272 DEBUG   Thread-4  :69158 [connectionpool.py:_make_request():461] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 59576
2021-08-23 14:53:27,333 DEBUG   SenderThread:69158 [sender.py:send():90] send: run
2021-08-23 14:53:27,336 DEBUG   SenderThread:69158 [git.py:repo():30] git repository is invalid
2021-08-23 14:53:27,336 DEBUG   SenderThread:69158 [git.py:repo():30] git repository is invalid
2021-08-23 14:53:27,341 DEBUG   SenderThread:69158 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-08-23 14:53:27,610 DEBUG   SenderThread:69158 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2021-08-23 14:53:27,613 DEBUG   HandlerThread:69158 [handler.py:handle_request():55] handle_request: run_start
2021-08-23 14:53:27,619 INFO    SenderThread:69158 [dir_watcher.py:__init__():165] watching files in: /home/sebastian/Documents/CQL/CQL-DQN/wandb/run-20210823_145326-ouvvtcg9/files
2021-08-23 14:53:27,620 INFO    SenderThread:69158 [sender.py:_start_run_threads():490] run started: ouvvtcg9 with start time 1629723206
2021-08-23 14:53:27,620 DEBUG   SenderThread:69158 [sender.py:send():90] send: summary
2021-08-23 14:53:27,620 INFO    SenderThread:69158 [sender.py:_save_file():568] saving file wandb-summary.json with policy end
2021-08-23 14:53:27,631 DEBUG   HandlerThread:69158 [git.py:repo():30] git repository is invalid
2021-08-23 14:53:27,695 DEBUG   SenderThread:69158 [sender.py:send():90] send: files
2021-08-23 14:53:27,696 INFO    SenderThread:69158 [sender.py:_save_file():568] saving file wandb-metadata.json with policy now
2021-08-23 14:53:27,697 DEBUG   HandlerThread:69158 [handler.py:handle_request():55] handle_request: status
2021-08-23 14:53:27,697 DEBUG   SenderThread:69158 [sender.py:send():90] send: request
2021-08-23 14:53:27,697 DEBUG   SenderThread:69158 [sender.py:send_request():99] send_request: status
2021-08-23 14:53:27,700 DEBUG   SenderThread:69158 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-08-23 14:53:27,705 DEBUG   Thread-11 :69158 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-08-23 14:53:27,950 DEBUG   SenderThread:69158 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2021-08-23 14:53:27,955 DEBUG   Thread-11 :69158 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2021-08-23 14:53:27,960 DEBUG   Thread-11 :69158 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): storage.googleapis.com:443
2021-08-23 14:53:28,414 DEBUG   Thread-11 :69158 [connectionpool.py:_make_request():461] https://storage.googleapis.com:443 "PUT /wandb-production.appspot.com/sebastian-dittert/uncategorized/ouvvtcg9/wandb-metadata.json?Expires=1629809607&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=ExqDgVumxU4RkZAJLmYjbyLCpSaDLZ1DAHzAmXcYxCRpSxMR1fMAmykzA46y7%2Bz1tastA51nJVP%2FDdbA1UhRbJfGjG6Kvp0j%2BSHyzTpvTqIeofDXfcyAN4tcBF5XFzpj7J3apOCxLhSEQ3uX9N6GXBcb3j3lWny%2F1GUMnwgOeDlJ58NeXFpc9ABrSnFxRjJj1waP%2BoslyopCsilQdRZILksEkEPpkst8vOErp%2BsAIw6Rw%2BOhmwvFruosYFJ1wFln%2BLyJUROjHSJntuj%2BZFk2SraaoZfq3u43RB2k6ofL27wPy6xSXADKUNqS8gZa5JuyQCOzVLRDvozKVrY8%2BsAsGQ%3D%3D HTTP/1.1" 200 0
2021-08-23 14:53:28,416 INFO    Thread-11 :69158 [upload_job.py:push():131] Uploaded file /tmp/tmps8itfkghwandb/34ostais-wandb-metadata.json
2021-08-23 14:53:28,622 INFO    Thread-8  :69158 [dir_watcher.py:_on_file_created():213] file/dir created: /home/sebastian/Documents/CQL/CQL-DQN/wandb/run-20210823_145326-ouvvtcg9/files/requirements.txt
2021-08-23 14:53:28,622 INFO    Thread-8  :69158 [dir_watcher.py:_on_file_created():213] file/dir created: /home/sebastian/Documents/CQL/CQL-DQN/wandb/run-20210823_145326-ouvvtcg9/files/wandb-metadata.json
2021-08-23 14:53:28,623 INFO    Thread-8  :69158 [dir_watcher.py:_on_file_created():213] file/dir created: /home/sebastian/Documents/CQL/CQL-DQN/wandb/run-20210823_145326-ouvvtcg9/files/output.log
2021-08-23 14:53:28,623 INFO    Thread-8  :69158 [dir_watcher.py:_on_file_created():213] file/dir created: /home/sebastian/Documents/CQL/CQL-DQN/wandb/run-20210823_145326-ouvvtcg9/files/wandb-summary.json
2021-08-23 14:53:29,772 DEBUG   Thread-5  :69158 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-08-23 14:54:11,148 WARNING Thread-5  :69158 [util.py:request_with_retry():707] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/sebastian-dittert/uncategorized/ouvvtcg9/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe5f016cc90>: Failed to establish a new connection: [Errno -2] Name or service not known')). args: ('https://api.wandb.ai/files/sebastian-dittert/uncategorized/ouvvtcg9/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{}']}}}}
2021-08-23 14:54:11,182 DEBUG   HandlerThread:69158 [handler.py:handle_request():55] handle_request: status
2021-08-23 14:54:11,262 DEBUG   SenderThread:69158 [sender.py:send():90] send: request
2021-08-23 14:54:11,262 DEBUG   SenderThread:69158 [sender.py:send_request():99] send_request: status
2021-08-23 14:54:11,457 DEBUG   SenderThread:69158 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
2021-08-23 14:54:12,376 DEBUG   SenderThread:69158 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2021-08-23 14:54:12,742 DEBUG   SenderThread:69158 [sender.py:send():90] send: stats
2021-08-23 14:54:13,434 DEBUG   Thread-5  :69158 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (2): api.wandb.ai:443
2021-08-23 14:54:14,267 DEBUG   Thread-5  :69158 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /files/sebastian-dittert/uncategorized/ouvvtcg9/file_stream HTTP/1.1" 200 None
2021-08-23 14:54:15,538 DEBUG   Thread-5  :69158 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /files/sebastian-dittert/uncategorized/ouvvtcg9/file_stream HTTP/1.1" 200 None
2021-08-23 14:54:21,790 DEBUG   SenderThread:69158 [sender.py:send():90] send: stats
2021-08-23 14:54:23,092 DEBUG   Thread-5  :69158 [connectionpool.py:_make_request():461] https://api.wandb.ai:443 "POST /files/sebastian-dittert/uncategorized/ouvvtcg9/file_stream HTTP/1.1" 200 None
2021-08-23 14:54:27,778 DEBUG   HandlerThread:69158 [handler.py:handle_request():55] handle_request: status
2021-08-23 14:54:27,970 DEBUG   SenderThread:69158 [sender.py:send():90] send: request
2021-08-23 14:54:28,122 DEBUG   SenderThread:69158 [sender.py:send_request():99] send_request: status
2021-08-23 14:54:29,045 DEBUG   SenderThread:69158 [connectionpool.py:_new_conn():975] Starting new HTTPS connection (1): api.wandb.ai:443
